### ISSUE TITLE
Helix's get constraints API does not response constraints with related preconfer pubkey

### ISSUE THREAD

**Issue by Akagi201** [lu-bann/helix#23]
Note that: preconfer pubkey may be not needed. Because when the validator is selected to propose a block, all the constraints should be its delegated preconfer if there is no errors.

Now the `/constraints/v1/constraint/{slot}` API only return a tx array constraint.

```json
{
  "slot": 0,
  "constraints": [
    [
      {
        "tx": "string"
      }
    ]
  ]
}
```

We need to add preconfer pubkey field

```sh
{
  "slot": 0,
  "constraints": [
    [
      {
        "preconfer_pubkey": "string"
        "tx": "string"
      }
    ]
  ]
}
```

The preconfer pubkey is useful for rbuilder and taiyi-boost local builder to distinguish the constraints, for example, local builder can do a filtering, only include its own configured preconfer's constraints.

Similiarly, Bolt has pubkey field: https://docs.boltprotocol.xyz/technical-docs/api/relay#constraints

**Comment by zsluedem** [comment]
@Akagi201 Do we still need this? I am closing it now. Feel free to reopen it if you think it is neccessary.
